### ISSUE TITLE
[타입과문법] Chap3. 네이티브

### ISSUE THREAD

**Issue by maywngml** [wldnswldnswl/IknowJS#11]
### 내용 정리
https://daily-crocodile-406.notion.site/3-3-4efc6d53abf24bcdb0eed710364ddc12

### 🤚질문
1. 박싱, 언박싱이란?
2. 값을 생성할 때 생성자로 만들면 오류 발생 확률이 높아지는 이유

**Comment by Joie-Kim** [comment]
내용 정리 미쳤다 !!!!!!
