### ISSUE TITLE
3장: 네이티브

### ISSUE THREAD

**Issue by Joie-Kim** [wldnswldnswl/IknowJS#13]
💣 note: [3장: 네이티브](https://www.notion.so/huijooooo/3-d716b1414a654b6fb348e54862aa4572)

### 질문 한 바가지...🤯
1. 리터럴 형태로 값을 생성한다는 게 무슨 뜻인지?
2. Array() 파트에서 map 함수로 i(인덱스)를 출력하는 부분
>- new Array(3)으로 생성한 배열은 길이가 이미 정해진 배열인데, 왜 인덱스로 접근이 안 될까?
3. 심벌.................(<s>ㅅㅂ</s>)
>- 그냥 전반적으로 이해가 잘 안 됐음
>- 그래서 왜 쓰는 거지? 언제 쓰는 거지?
4. 프로토타입
>- 프로토타입에 대해 잘 알고 계시는 분이 있을까요..? (<s>구글링 안 하는 핑프 같나요..?ㅠ</s>)
>- '프로토타입을 변경할 수는 있지만, 이는 바람직한 발상이 아니다.' ➡️ 프로토타입을 변경한다는 게 무슨 뜻인지..?

**Comment by wldnswldnswl** [comment]
eval 함수
https://support.microsoft.com/ko-kr/office/eval-%ED%95%A8%EC%88%98-8c4a1b10-85ba-40db-b0c8-5290da4d4166

**Comment by Joie-Kim** [comment]
고마워용!
