### ISSUE TITLE
[타입과문법] 4.3.명시적 강제변환

### ISSUE THREAD

**Issue by maywngml** [wldnswldnswl/IknowJS#18]
### 요점 정리
https://daily-crocodile-406.notion.site/5-4-3-5a75dcef94e847559814f9936b3bebd4

### 질문
1. (p103) ToInt32은 ToNumber 강제변환한다?? “123”이면 ToInt32 적용하기 전 123으로 바꾼다?? 말의 의미를 정확히 파악하지 못했음
2. 경계 값이란 뭐지??
3. `const a = "hello world";  ~a.indexOf("lo")`은 왜 -4지? a.indexOf("lo")는 3인데 뭐지?! 그냥 truthy한 값으로 아무렇게나 바뀌는 건가??

**Comment by wldnswldnswl** [comment]
[~~ vs Math.floor]
~~-6.8 == -6 // doesn’t round down, simply removes the decimals
Math.floor(-6.8) == -7

**Comment by maywngml** [comment]
1. 문자열을 ToNumber로 64비트로 변경한 다음에 ToInt32를 써서 32비트 숫자로 바꿔준다는 뜻
2. 약속의 의미..? 예를 들어 c언어를 만든 사람이 -1은 실패라는 뜻이야~! 앞으로 이렇게 쓰자~! 하며 다같이 약속한 값이라는 의미인걸까 확실하진 않지만 이런 느낌임
3. 3을 이진법으로 변환한 후에 2의 보수로 변경하면 -4가 나옴, 틸드 연산자가 어떤 연산자인지를 파악하면 이해할 수 있었어
