### ISSUE TITLE
[타입과 문법] Chap2.값

### ISSUE THREAD

**Issue by maywngml** [wldnswldnswl/IknowJS#2]
### 배열
1. 크기를 정하지 않은 배열에 인덱스로 접근해서 값을 추가할 수 있다.
2. 0 ~ 2번째 원소 값을 지정하지 않고 3번째 인덱스에 값을 추가하면 0 ~ 2번째 원소는 undefined가 된다
    => 구멍난(sparse) 배열이라고 함
`const temp = [];
temp[3] = 3;
 temp => undefined, undefined, undefined, 3`
3. 배열도 하나의 객체여서 키/프로퍼티 문자열을 추가할 수 있음, 하지만 추가해도 배열의 길이는 변하지 않음

### 문자열
1. 문자열은 불변 배열 메서드를 빌려 쓸 수 있다.
    => 문자열은 불변 값이기 때문에 내용이 변경될 수 없다.
`Array.prototype.join.call()`

### 숫자
1. 0.1과 0.2는 진짜 0.1, 0.2이 아니다. 이 둘을 더한 실제값은 0.30000000000000004이다.

## 질문
1. Array.prototype.배열 메소드.call의 동작 원리
2. 자바스크립트에서 소수값이 원래 숫자와 일치하지 않는 이유

**Comment by Joie-Kim** [comment]
### Array.prototype.배열 메소드.call의 동작 원리
- 책에서 배열(Array)이 객체의 하위 타입이라고 했음. 즉, 내부에 프로퍼티를 가지고 있음.
- 함수(function) 또한 객체의 하위 타입으로 내부의 call 프로퍼티를 사용해 호출할 수 있다는 특징이 있음.
- 따라서 배열 안에 있는 함수(메소드)를 호출하기 위해 해당 함수 내에 있는 call 프로퍼티를 사용한 것으로 이해함.

### 자바스크립트에서 소수값이 원래 숫자와 일치하지 않는 이유
- 자바스크립트에서는 부동 소수점 방식을 사용하고, 부동 소수점은 지수부와 가수부를 나누어 메모리에 저장하는 방식임.
- 지수부와 가수부로 나누는 방식은 근사값을 표현하는데, 예를 들어 0.299886989678968799...라는 수를 0.3으로 표현함.
- 따라서 완벽하게 일치하지 않음 !!

---

@maywngml  저번에 얘기 했던 내용 간략하게 정리했슴다!

**Comment by maywngml** [comment]
궁금증 해결 완료!!
