### ISSUE TITLE
[아키텍처] 6장. 아키텍처 특성의 측정 및 거버넌스

### ISSUE THREAD

**Issue by maywngml** [wldnswldnswl/IknowJS#231]
### 요점정리
https://daily-crocodile-406.notion.site/6-10a3665b58f280c59ceedd7336912cc2?pvs=4

### 질문
1. (p.118) 순환 복잡도 예시 N = 5, E = 4 여서 정답은 1 아닌가요..?? 아무래도 공식 N이랑 E를 바꿔서 쓴 것 같은데

**Comment by Seulwoo** [comment]
https://github.com/wldnswldnswl/IknowJS/issues/229#issue-2541060167
>0< 웰컴 ~~
