### ISSUE TITLE
2.4.바인딩 예외 ~ 3.2.1.내장 객체

### ISSUE THREAD

**Issue by maywngml** [wldnswldnswl/IknowJS#55]
### 요점 정리
https://daily-crocodile-406.notion.site/16-2-4-3-2-5679b7db9a3042e89914dea18125497a

### 질문
1. (p.60) p.foo = o.foo의 결괏값은 원 함수 객체의 레퍼런스이다.
    => o.foo는 foo 레퍼런스를 소유하고 있고 이걸 p객체에게 할당한 거니까 p.foo의 결괏값이 원 함수 객체(foo)의 레퍼런스라고 말하는 게 맞나?
2. 소프트 바인딩은 전역 객체나 undefined가 아닌 값으로 기본 바인딩을 적용하고 싶을 때 사용하는 것으로 이해하면 되는 것인지?
3. (p. 61) setTimeout구문에서 소프트 바인딩이 적용된 이유
    => obj.foo를 명시적으로 호출한게 아니어서 기본 객체(obj)로 기본 바인딩이 적용된 것인지??
4. 복합 원시 타입이란?

**Comment by Joie-Kim** [comment]
(p.foo = o.foo).();
p.foo = o.foo => function () {...} => foo()

(function () {....}).();

**Comment by Joie-Kim** [comment]
foo.apply(obj); // this 명시적 선언
tempObj = {}; // 기본 바인딩의 default 값으로 쓰고 싶어서 ??

**Comment by maywngml** [comment]
복합 원시 타입 = 단순 원시 타입이 여러개 있는 객체

**Comment by wldnswldnswl** [comment]
> setTimeout(function () {...}, time)
> 
> setTimeout(obj2.foo, 10) obj2.foo => foo() {...} // 기본 바인딩 적용 > obj 기본으로 해놔서 > obj가 나온 느낌!?
> 
> obj2.foo(); // 호출문 > obj2 암시적(??) 바인딩

참고용 링크 남깁니당: https://joooing.tistory.com/entry/setTimeout%ED%95%A8%EC%88%98%EC%97%90%EC%84%9C%EC%9D%98-this%EA%B0%92-%EB%B3%80%ED%99%94

**Comment by maywngml** [comment]
1. (p.foo = o.foo)() ⇒ (function () {...})() => foo() foo 그 자체가 됨.
2. 소프트 바인딩은 전역 객체나 undefined가 아닌 값으로 기본 바인딩을 적용하고 싶을 때 사용하는 것이 맞음
3. obj2.foo()는 obj2가 this 바인딩 된 foo 함수를 호출하는 것! obj2.foo ⇒ foo(){…} obj.foo는 foo 그 자체! obj가 기본 바인딩 된  foo가 실행된다.
4. 복합 원시 타입은 단순 원시 타입이 여러개 있는 객체
