### ISSUE TITLE
part2) 1장 : 비동기성 지금과 나중

### ISSUE THREAD

**Issue by Joie-Kim** [wldnswldnswl/IknowJS#91]
## Note
- [1장 : 비동기성 지금과 나중](https://www.notion.so/huijooooo/1-2d99bcf595084c7b8d07885d8a3c73ad?pvs=4)

### 1.2 이벤트 루프
- setTimeout( )에 대한 이야기가 나온다.
>- 적어도 지정한 시간(Interval) 이전에 콜백이 실행되지 않을 거란 사실은 보장할 수 있지만, 정확히 언제 혹은 좀 더 시간이 경과한 이후에 실행될지는 이벤트 루프 큐의 상황에 따라 달라진다.
- 이런 이유로 현업에서 setTimeout( )을 잘 사용하지 않게 된다. 혹시 다른 분들은 어떤 식으로 사용하고 있는지 궁금하다. 
### 1.3 병렬 스레딩
- 무슨 말인지 이해가 잘 안 됨..
>- 반면 이벤트 루프는 작업 단위로 나누어 차례대로 실행하지만, 공유 메모리에 병렬로 접근하거나 변경할 수는 없다. 병렬성(Parallelism)과 직렬성(Serialism)이 나뉜 스레드에서 이벤트 루프를 협동(Cooperation)하는 형태로 공존하는 모습이다.
### 1.4 동시성
- 무슨 말인지 이해가 잘 안 됨... (이번 장에는 어려운 말로 설명하는 게 많이 나오는 거 같아요 ㅠㅠ)
>- 동시성은 처리 수준(operation-level) 병행성과 상반되는 개념의 프로세스 수준(process-level)의 병행성이라 할 수 있다.

### 인터리빙 (Interleaving)
- 참고 링크 : [병행성의 원리](https://yeol-study-history.tistory.com/49)
>- 글을 읽다보니 어려운 개념들이 많네요.... 그치만 알아둬야겠죠......... (해도 해도 공부할 게 끊임없는 개발이란.........ha🤦🏻‍♀️)
### 동시성 (Concurrency)
- 참고 링크 : [동시성과 병렬성의 차이 알아보기](https://sas-study.tistory.com/446)
- 책에 나왔던 구문
>- 동시성은 복수의 ‘프로세스’가 같은 시간 동안 동시에 실행됨을 의미하며, 각 프로세스 작업들이 병렬로 처리되는지와는 관계없다.

**Comment by wldnswldnswl** [comment]
js setTimeout == java Thread.sleep()
- 마이그레이션처럼 긴 시간동안 대량의 데이터를 보정해야할때 bulk로 짜르는 데이터량을 정하고 그 양만큼 처리 후  일정시간 sleep한다.
- (주로 테스트 코드에서) 캐시 evict 반영되는 시간
- (주로 테스트 코드에서) 비동기 결과가 빨리 도착했을 때 or 저희코드에서 1:1 전파를 먼저 하고 백그라운드에서 1:N 전파를 하는 부분이 있는데 1:N 전파가 수행 완료되는 것을 기다리기 위해 sleep.
